const machines = [
  {
    machineId: "M001",
    name: "ECG Machine",
    department: "Cardiology",
    manufacturer: "Medtronic",
    model: "CardioScan 3000",
    availability: "Available",
    maintenanceDue: "2025-03-15",
  },
  {
    machineId: "M002",
    name: "Defibrillator",
    department: "Cardiology",
    manufacturer: "Philips",
    model: "HeartStart FR3",
    availability: "In Use",
    maintenanceDue: "2024-12-20",
  },
  {
    machineId: "M003",
    name: "Ultrasound Machine",
    department: "Pediatrics",
    manufacturer: "GE Healthcare",
    model: "Voluson E10",
    availability: "Available",
    maintenanceDue: "2025-01-25",
  },
  {
    machineId: "M004",
    name: "MRI Scanner",
    department: "Neurology",
    manufacturer: "Siemens",
    model: "Magnetom Lumina",
    availability: "In Use",
    maintenanceDue: "2024-11-10",
  },
  {
    machineId: "M005",
    name: "CT Scanner",
    department: "Neurology",
    manufacturer: "Toshiba",
    model: "Aquilion Prime",
    availability: "Available",
    maintenanceDue: "2025-02-18",
  },
  {
    machineId: "M006",
    name: "Dermatoscope",
    department: "Dermatology",
    manufacturer: "Heine",
    model: "Delta 20T",
    availability: "Available",
    maintenanceDue: "2024-10-30",
  },
  {
    machineId: "M007",
    name: "X-Ray Machine",
    department: "Orthopedics",
    manufacturer: "Shimadzu",
    model: "MobileDaRt Evolution",
    availability: "In Use",
    maintenanceDue: "2025-05-12",
  },
  {
    machineId: "M008",
    name: "Bone Densitometer",
    department: "Orthopedics",
    manufacturer: "Hologic",
    model: "Discovery QDR",
    availability: "Available",
    maintenanceDue: "2025-04-08",
  },
  {
    machineId: "M009",
    name: "Fetal Monitor",
    department: "Gynecology",
    manufacturer: "Philips",
    model: "Avalon FM20",
    availability: "Available",
    maintenanceDue: "2025-01-05",
  },
  {
    machineId: "M010",
    name: "Audiometer",
    department: "ENT",
    manufacturer: "Interacoustics",
    model: "AD629",
    availability: "In Use",
    maintenanceDue: "2024-12-02",
  },
  {
    machineId: "M011",
    name: "Otoscope",
    department: "ENT",
    manufacturer: "Welch Allyn",
    model: "MacroView 23810",
    availability: "Available",
    maintenanceDue: "2025-03-22",
  },
  {
    machineId: "M012",
    name: "Infusion Pump",
    department: "General Medicine",
    manufacturer: "B. Braun",
    model: "Infusomat Space",
    availability: "In Use",
    maintenanceDue: "2025-02-17",
  },
  {
    machineId: "M013",
    name: "Ventilator",
    department: "General Medicine",
    manufacturer: "Dräger",
    model: "Evita V300",
    availability: "Available",
    maintenanceDue: "2025-04-25",
  },
  {
    machineId: "M014",
    name: "Dialysis Machine",
    department: "General Medicine",
    manufacturer: "Fresenius",
    model: "4008S",
    availability: "In Use",
    maintenanceDue: "2025-01-11",
  },
  {
    machineId: "M015",
    name: "Electrosurgical Unit",
    department: "Gynecology",
    manufacturer: "Erbe",
    model: "VIO 300 D",
    availability: "Available",
    maintenanceDue: "2025-03-18",
  },
  {
    machineId: "M016",
    name: "Colposcope",
    department: "Gynecology",
    manufacturer: "Leisegang",
    model: "Optik",
    availability: "In Use",
    maintenanceDue: "2025-02-14",
  },
  {
    machineId: "M017",
    name: "EEG Machine",
    department: "Neurology",
    manufacturer: "Natus",
    model: "Quantum",
    availability: "Available",
    maintenanceDue: "2025-06-07",
  },
  {
    machineId: "M018",
    name: "Incubator",
    department: "Pediatrics",
    manufacturer: "GE Healthcare",
    model: "Giraffe Omnibed",
    availability: "In Use",
    maintenanceDue: "2024-12-25",
  },
  {
    machineId: "M019",
    name: "Spirometer",
    department: "General Medicine",
    manufacturer: "MIR",
    model: "Spirolab",
    availability: "Available",
    maintenanceDue: "2025-05-01",
  },
  {
    machineId: "M020",
    name: "Nebulizer",
    department: "Pediatrics",
    manufacturer: "Omron",
    model: "NE-C801",
    availability: "Available",
    maintenanceDue: "2025-01-29",
  },
];


export default machines;